### ISSUE TITLE
Integration tests should not be run in production

### ISSUE THREAD

**Issue by rockstar** [lxc/pylxd#118]
Integration tests should make sure their environment is clean of existing images and containers before trying to run. We can't guarantee they won't delete everything, or manipulate true containers in a way that makes them lose data, etc.

Integration tests should bomb out if there's any pre-existing data.

**Comment by jpic** [comment]
So, contributors won't even be able to run them on development workstations ? Perhaps the test could start an lxd instance in the background then.

**Comment by rockstar** [comment]
Fixed in #125
