### ISSUE TITLE
Add usage documentation

### ISSUE THREAD

**Issue by monokal** [lxc/pylxd#123]
There's currently no useful usage documentation for anyone stumbling upon pylxd which means they usually revert back to using the LXD API via the requests module, also meaning we're missing out on potential contributors. Simple usage documentation would resolve this, at least enough for other contributors to build upon without having to dig through tons of code.

Edit: I see there's some generated docs in doc/source but it's not referenced from the README.

**Comment by rockstar** [comment]
![screenshot 2016-05-31 08 27 49](https://cloud.githubusercontent.com/assets/60306/15677909/80119f2a-2709-11e6-81e2-76f256f82fb3.png)

If you click on the image that says "docs | latest", you'll get taken to http://pylxd.readthedocs.io/en/latest/ where there is extensive usage documentation for all the current features of pylxd.
