### ISSUE TITLE
Container.update needs better documentation

### ISSUE THREAD

**Issue by hnakamur** [lxc/pylxd#141]
Currently we can specify config for a container only when we create a container: [pylxd/container.py at 865ec541bc44b7915502a63a3764ada98a7465cf · lxc/pylxd](https://github.com/lxc/pylxd/blob/865ec541bc44b7915502a63a3764ada98a7465cf/pylxd/container.py#L103)
Could you add a method to Container for updating configuration?
With the LXD REST API [PUT /1.0/containers/<name>](https://github.com/lxc/lxd/blob/master/doc/rest-api.md#put-etag-supported-1), you can update configuration of a container.

**Comment by rockstar** [comment]
The way you would do this is by getting the container, modifying it's `config` attribute, and then calling `update()` on the object.

I think this issue really should be about documenting how to do this in our documentation (which is, admittedly, light).

**Comment by rockstar** [comment]
Fixed in #154
