### ISSUE TITLE
container.profiles are not updated after updating profiles

### ISSUE THREAD

**Issue by hnakamur** [lxc/pylxd#146]
In my environment, I created the profile named "bridged".

I tried the following script.
```
from pylxd.client import Client

client = Client()
container = client.containers.get('myubuntu2')
print(container.profiles)

container.profiles = ['default', 'bridged']
container.update()

container = client.containers.get('myubuntu2')
print(container.profiles)
```

I got the following output.
```
[u'default']
[u'default']
```

Actually the profiles are applied to the container.
```
$ lxc config show --expanded myubuntu2
name: myubuntu2
profiles:
- default
- bridged
config:
  limits.cpu: "2"
  volatile.base_image: ed0fb49ea8c3698c96c14157dff05b8c55eab2db438d3b043af1037836f1fa2b
  volatile.eth0.hwaddr: 00:16:3e:ef:d4:f6
  volatile.eth0.name: eth1
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
devices:
  eth0:
    nictype: bridged
    parent: br0
    type: nic
  root:
    path: /
    type: disk
ephemeral: false
```

So I think the output should become like the following:
```
[u'default']
[u'default', u'bridged']
```

I installed pylxd with `pip install git+https://github.com/lxd/pylxd`
```
$ pip list | grep pylxd
pylxd (2.0.3.dev20)
```

**Comment by rockstar** [comment]
`Container.update` is an "async" call in LXD. That means that you make the request, but the changes aren't necessarily applied by the time the response from HTTP comes back. If you want your code to block until the operation is complete, you pass `wait=True` to `Container.update`. This would make your script look like this:

```
from pylxd.client import Client

client = Client()
container = client.containers.get('myubuntu2')
print(container.profiles)

container.profiles = ['default', 'bridged']
container.update(wait=True)

container = client.containers.get('myubuntu2')
print(container.profiles)
```

**Comment by hnakamur** [comment]
Thanks for your comment.
I confirmed that I got the updated profiles when I pass `wait=True` to `Container.update`.

**Comment by rockstar** [comment]
@hnakamur most of the lxd team idle in #lxc-dev on Freenode. I'd be happy to answer questions there as well.
