### ISSUE TITLE
Migration fails

### ISSUE THREAD

**Issue by zulcss** [lxc/pylxd#162]
DBUG[07-24|19:06:46] ContainerCreate                          driver=storage/zfs name=chuck isPrivileged=false
DBUG[07-24|19:06:46] ContainerStart                           driver=storage/zfs container=chuck
DBUG[07-24|19:06:46] ContainerStop                            driver=storage/zfs container=chuck
EROR[07-24|19:06:46] Error during migration sink              err="lookup http+unix: invalid domain name"
DBUG[07-24|19:06:46] containerDeleteSnapshots                 container=chuck
DBUG[07-24|19:06:46] ContainerDelete                          driver=storage/zfs container=chuck
DBUG[07-24|19:06:47] Failure for task operation: 4b69f75b-e63c-4626-82b7-7c4573f68d63: Error transferring container data: lookup http+unix: invalid domain name 
INFO[07-24|19:09:30] handling                                 method=GET url=/1.0 ip=@
DBUG[07-24|19:09:30]

**Comment by pcdummy** [comment]
LXD needs a `https://` URI for migrations to work, you need to create an instance of pylxd.Client() with the endpoint, cert and surely verify set.

**Comment by zulcss** [comment]
This is what Im doing:

from pylxd import client

c = client.Client()

profile = c.profiles.create('chuck', config={}, devices={})
container_config = {
   'name': 'chuck',
   'profiles': ['chuck'],
   'source': {
    'type': 'image',
    'alias':  '5399a9b2-a314-42a4-8627-2112e2be0761'
   }
}
container = c.containers.create(container_config, wait=True)
container.start(wait=True)

remote = client.Client(endpoint='https://m2:8443',
                      cert=('/home/ubuntu/.config/lxc/client.crt', '/home/ubuntu/.config/lxc/client.key'),
                      verify=False)
Rprofile = remote.profiles.create(profile.name, config=profile.config, devices=profile.devices)
a_container = c.containers.get('chuck')

a_migrated_container = a_container.migrate(remote)

**Comment by pcdummy** [comment]
@zulcss The first "c = client.Client()" needs to be 
```python
client.Client("https://<a-remote-available-ip-or-hostname>:8443", ("<cert-path>", "<key-path>",), False)
```

You might need to do "lxc remote add m2 https://m2:8443" and "lxc remote add m1 https://m1:8443"

**Comment by pcdummy** [comment]
And as a note, i think this is prefered:

```python
import pylxd
c = pylxd.Client(endpoint="endpoint", cert="", verify=False)
```

**Comment by rockstar** [comment]
I've been racking my brain trying to figure out how to fix this. In some cases, `/1.0` should return the public ip address in `metadata.config.core.https_address`, but my current setting for that is `0.0.0.0:8443`, so clearly that's not going to work. In `metadata.environment.addresses` there is a list of addresses, but I currently have *4* (WTF?) addresses there. @zulcss, thoughts?

**Comment by zulcss** [comment]
Well URL is taken from whatever is in lxc remote list but Im not sure how to handle it either.
