### ISSUE TITLE
Can't get the output of container.execute

### ISSUE THREAD

**Issue by madbobmcjim** [lxc/pylxd#186]
I'm trying to print the output of the execute command as a part of some automation work.

The following function works fine:
```
def appInsallContainer(inContainerName, packages):
        container = lxdClient.containers.get(inContainerName)
        containerExec = ['apt install -y '+packages]
        container.execute(containerExec)
```

This function errors:
```
def appInsallContainer(inContainerName, packages):
        container = lxdClient.containers.get(inContainerName)
        containerExec = ['apt install -y '+packages]
        stdout,stderr=container.execute(containerExec)
        print '-'.join(stdout)
        print '-'.join(stderr)
```
With:
`TypeError: 'NoneType' object is not iterable`

Any idea what I'm doing wrong?

**Comment by eistin** [comment]
Why use join?
For me, it works with:
```
def appInsallContainer(inContainerName, packages):
        container = lxdClient.containers.get(inContainerName)
        containerExec = ['apt install -y '+packages]
        stdout,stderr=container.execute(containerExec)
        print '-' + stdout
        print '-' + stderr
```

**Comment by madbobmcjim** [comment]
Thanks for getting back to me. Replacing the join doesn't make any difference, the error is in the .execute line:

```
Traceback (most recent call last):
  File "build.py", line 20, in <module>
    functions.appInsallContainer(containerName, packages)
  File "/home/mephi/ContainerBuild/LXDbuild/functions.py", line 95, in appInsallContainer
    stdout,stderr=container.execute(containerExec)
TypeError: 'NoneType' object is not iterable
```

I'm using version version 2.0.0-0ubuntu1 installed from apt on Ubuntu 16.04 if that makes any difference.

**Comment by eistin** [comment]
Do you mean Pylxd v2.0.0 ?
If yes, upgrade pylxd to version 2.1.1  and your problem should be resolved.
I can't reproduce your error with the same code.

**Comment by rockstar** [comment]
Pylxd prior to 2.0.3 had some issues with `execute` - Upgrade pylxd, and if you've still got the issue, feel free to reopen.
