### ISSUE TITLE
Execute not working

### ISSUE THREAD

**Issue by madbobmcjim** [lxc/pylxd#201]
Hi, I'm still having trouble with the execute function. It's not actually executing anything at all.

The code I'm using is:
```
>>> from pylxd import client
>>> lxdClient = client.Client()
>>> containerName = "snmp2"
>>> containerExec = ["mkdir /go"]
>>> container = lxdClient.containers.get(containerName)
>>> container.execute_with_result(containerExec)
ContainerExecuteResult(exit_code=255, stdout=u'', stderr=u'')
```
I've tried execute as well as execute_with_result.

Using the lxc command works fine:
`lxc exec snmp2 -- mkdir /go`

It's on Ubuntu 16.04 with the standard Ubuntu versions of LXC/LXD, and the latest pylxd from pip.

In the /var/log/lxd/lxd.log file the following lines are created, the first two from pylxd, the second from 'lxc exec':
```
t=2016-11-22T15:02:29+0000 lvl=info msg="Executing command" environment="[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin]" args="[/usr/bin/lxd forkexec snmp2 /var/lib/lxd/containers /var/log/lxd/snmp2/lxc.conf -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin -- cmd mkdir /go]"
t=2016-11-22T15:02:30+0000 lvl=info msg="Executed command" environment="[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin]" args="[/usr/bin/lxd forkexec snmp2 /var/lib/lxd/containers /var/log/lxd/snmp2/lxc.conf -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin -- cmd mkdir /go]" exit_status=255

t=2016-11-22T15:03:06+0000 lvl=info msg="Executing command" environment="[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HOME=/root TERM=xterm USER=root]" args="[/usr/bin/lxd forkexec snmp2 /var/lib/lxd/containers /var/log/lxd/snmp2/lxc.conf -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HOME=/root TERM=xterm USER=root -- cmd mkdir /go]"
t=2016-11-22T15:03:06+0000 lvl=info msg="Executed command" environment="[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HOME=/root TERM=xterm USER=root]" args="[/usr/bin/lxd forkexec snmp2 /var/lib/lxd/containers /var/log/lxd/snmp2/lxc.conf -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HOME=/root TERM=xterm USER=root -- cmd mkdir /go]"
```

Any idea how I debug this?

**Comment by larryprice** [comment]
Your containerExec needs to be an array of strings split on spaces. I recommend using shlex.split:

``` python
import pylxd
import shlex

client = pylxd.Client()
container = client.containers.get('snmp2')
container.execute_with_result(shlex.split('mkdir /go'))
```

**Comment by madbobmcjim** [comment]
That did it, thanks :-)
Do you know if I have to split environment variables too?

**Comment by larryprice** [comment]
If you include environment variables as part of the command, they need to be split. If you use the `env` kwarg to pass in environment variables, then you can use a python dict.

``` python
# as part of the command
container.execute_with_result(shlex.split('LANGUAGE=en_US mkdir /go'))

# as kwarg
container.execute_with_result(shlex.split('mkdir /go'), env={'LANGUAGE': 'en_US'})

# bonus - copy local env
modified_env = os.environ.copy()
modified_env['LAUNGUAGE'] = 'en_US'
container.execute_with_result(shlex.split('mkdir /go'), env=modified_env)
```

**Comment by madbobmcjim** [comment]
Ahh yes. I was looking to use kwarg option as go needs some environment variables to run.

Thanks for your help :-)

**Comment by madbobmcjim** [comment]
I think I'm having troubles with environment variables again. I'm happy to use them as part of the command which you listed, but it doesn't seem to be working. I'm trying to get an unattended apt update working, and it was hanging because it was waiting for user input. I'm not sure if it's a regression (I updated via pip while trying to figure out what was going on) but it's failing for me.

```
# the actual command I'm trying to get working:
container.execute(shlex.split('DEBIAN_FRONTEND=noninteractive DEBIAN_PRIORITY=critical apt-get -q -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold" upgrade'))

# the log entry that appears:
lxc 20160220152938.422 ERROR    lxc_attach - attach.c:lxc_attach_run_command:1292 - No such file or directory - Failed to exec "DEBIAN_FRONTEND=noninteractive".

# testing out your previous code to see if that errors:
>>> container.execute(shlex.split('LANGUAGE=en_US mkdir /go'))
ContainerExecuteResult(exit_code=255, stdout=u'', stderr=u'')

# its log message
lxc 20160220153159.154 ERROR    lxc_attach - attach.c:lxc_attach_run_command:1292 - No such file or directory - Failed to exec "LANGUAGE=en_US".

```

Any idea what I'm doing wrong here?

Ubuntu 16.04 LXD from standard repos, pylxd (2.2.2) from pip.

**Comment by stgraber** [comment]
@madbobmcjim LXD doesn't execute those commands through a shell, so those leading env variables are meaningless to it and interpreted as the binary name instead (which obviously won't work).

I think you want:

     container.execute(shlex.split('env DEBIAN_FRONTEND=noninteractive DEBIAN_PRIORITY=critical apt-get -q -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold" upgrade'))

**Comment by madbobmcjim** [comment]
That got it, thanks. :-)
