### ISSUE TITLE
AttributeError: last_used_at on a *container* object

### ISSUE THREAD

**Issue by szymi-** [lxc/pylxd#213]
The following example of using a container object attribute results an error analogical to the (already resolved) one reported here for an image object: https://github.com/lxc/pylxd/issues/165 

    In [1]: import pylxd
    In [2]: client = pylxd.Client()
    In [3]: first_image = client.images.all()[0]
    In [4]: first_container = client.containers.all()[0]
    In [5]: first_container.__attributes__
    Out[5]: 
    {'architecture': <pylxd.models._model.Attribute at 0x7f1147d77780>,
     'config': <pylxd.models._model.Attribute at 0x7f1147d777b8>,
     'created_at': <pylxd.models._model.Attribute at 0x7f1147d777f0>,
     'devices': <pylxd.models._model.Attribute at 0x7f1147d77828>,
     'ephemeral': <pylxd.models._model.Attribute at 0x7f1147d77860>,
     'expanded_config': <pylxd.models._model.Attribute at 0x7f1147d77898>,
     'expanded_devices': <pylxd.models._model.Attribute at 0x7f1147d778d0>,
     'last_used_at': <pylxd.models._model.Attribute at 0x7f1147d779b0>,
     'name': <pylxd.models._model.Attribute at 0x7f1147d77908>,
     'profiles': <pylxd.models._model.Attribute at 0x7f1147d77940>,
     'stateful': <pylxd.models._model.Attribute at 0x7f1147d77a20>,
     'status': <pylxd.models._model.Attribute at 0x7f1147d77978>,
     'status_code': <pylxd.models._model.Attribute at 0x7f1147d779e8>}

As seen above, the *last_used_at* attribute is available. However accessing it results in an error:

     In [6]: first_container.last_used_at
    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    /home/ubuntu/venv/lib/python3.5/site-packages/pylxd/models/_model.py in __getattribute__(self, name)
        118         try:
    --> 119             return super(Model, self).__getattribute__(name)    
        120         except AttributeError:

    AttributeError: last_used_at

    During handling of the above exception, another exception occurred:

    AttributeError                            Traceback (most recent call last)
    <ipython-input-6-1ae57d91a110> in <module>()
    ----> 1 first_container.last_used_at

    /home/ubuntu/venv/lib/python3.5/site-packages/pylxd/models/_model.py in __getattribute__(self, name)
        121             if name in self.__attributes__:
        122                 self.sync()
    --> 123                 return super(Model, self).__getattribute__(name)
        124             else:
        125                 raise

    AttributeError: last_used_at

**Comment by ChrisMacNaughton** [comment]
This looks like it has been fixed:

```
>>> import pylxd
>>> client = pylxd.Client()
>>> client.images.all()
[<pylxd.models.image.Image object at 0x7ff1e4372c80>]
>>> image = client.images.all()[0]
>>> first_container = client.containers.all()[0]
>>> first_container.last_used_at
'2017-09-26T18:56:05.757122222Z'
```
