### ISSUE TITLE
Please provide 2.2.2 release tag

### ISSUE THREAD

**Issue by ganto** [lxc/pylxd#219]
On pypi there is a `pylxd-2.2.2` version available which is not appropriately tagged on Github. Is there any reason for this or could you please still push the tag?

Kind regards.

**Comment by stgraber** [comment]
Sounds like @rockstar forgot to pass --tags :)

https://github.com/lxc/pylxd/commit/39f1ec314ab4965984a8a4246563287e4d5c35f6 should indeed have a 2.2.2 tag.

**Comment by ajkavanagh** [comment]
I'm guessing this is overtaken by events (i.e. there are now more recent versions).  If not, please shout!

**Comment by ganto** [comment]
What's the issue with pushing a tag? Sure, it's not super relevant to me anymore but I still feel it should be relevant for the completeness of this repository.

**Comment by ajkavanagh** [comment]
Okay, I've pushed the tag to the commit that was made on the same day as the date of the release to PyPi.  Also the context seems to be the same; but I can't actually guarantee it's the right commit.

I can't do an old 'release' via GitHub as they don't seem to allow it via the GUI; the API may allow it, but I'm not inclined to spend a lot of time working out how to do it.
