### ISSUE TITLE
ws4py isn't actively maintained, look for alternatives.

### ISSUE THREAD

**Issue by om26er** [lxc/pylxd#223]
The project maintainer says that he is no longer interested in the project. We need to look for alternatives for pylxd.

blogpost: http://www.defuze.org/archives/409-ws4py-is-eager-for-a-new-maintainer.html

**Comment by rockstar** [comment]
I was afraid this was going to happen. Maintaining backwards compatibility will be difficult. :/

**Comment by om26er** [comment]
Much have changed since I reported this bug. I think we could use [Autobahn Python](https://github.com/crossbario/autobahn-python) as a replacement for ws4py. Its very well maintained, more feature rich, has been in active development for a long time and is currently being used in production by many projects. Firefox being the biggest user.

@rockstar can you highlight the challenges you see in maintaining backwards compatibility ?

Disclaimer: Crossbar.io, my employer is the maintainer of that project.

**Comment by ajkavanagh** [comment]
Having just found this: https://groups.google.com/forum/#!topic/ws4py/Dr-yCUWwZ1Q

> My name is Mathieu, and stepped up to maintain ws4py. Thanks a lot to Sylvain for accepting new contributors!
> The 0.3.5 was released almost 2 years ago, and the pip version was now obsolete.
> 
> A new version 0.4.0 is released from latest master. The most notable changes are:
> - fixes to support latest CherryPy
> - fixes issue for bad networking / interrupt / client that disconnect ungracefully
>
> Just `pip install ws4py` and you're good to go :)

I feel the urgency to shift away from ws4py is reduced.  Are there any pressing reasons to make the move to something else?  (e.g. something we can't do that we want to do with the library?).  Thanks.

**Comment by om26er** [comment]
If ws4py has a new maintainer then I don't see any reason to move away from it. The original bug report came as a reaction to the blogpost linked above. So maybe we should close this issue ?

**Comment by ajkavanagh** [comment]
Yes, I agree.  We can always re-open it if needed in the future.  Thanks.

**Comment by lingfish** [comment]
So, I'm having major issues with ws4py, and it looks like it's back in hiatus status.
