### ISSUE TITLE
How to reuse current lxc setup?

### ISSUE THREAD

**Issue by techtonik** [lxc/pylxd#226]
I want pylxd.Client() to open my default remote that is configured for `lxc` command line tool. I also want to reuse the connection setting - ip and certificate. Is that possible?

**Comment by ajkavanagh** [comment]
If you're remote server is running the lxd daemon *and* it is configured for remote access, then yes, this is possible.  @stgraber 's post [LXD 2.0: Remote hosts and container migration](https://stgraber.org/2016/04/12/lxd-2-0-remote-hosts-and-container-migration-612/) has some information about how to set up the remote access.

Then to actually use it you'd authenticate as per the [docs](https://github.com/lxc/pylxd/blob/master/doc/source/authentication.rst).

Does this help?

**Comment by techtonik** [comment]
I understand this, but the question is about reusing `lxc` setup, not about configuring `pylxd` once more for the parameters that are already there.

**Comment by ChrisMacNaughton** [comment]
@techtonik pylxd, by default, will try to connect to a local LXD socket. The client _can_ be configured to connect to a remote host but currently does not read any machine-local lxd configuration

**Comment by ajkavanagh** [comment]
@techtonik is this still relevant to you?  If so, please can you explain what you are looking for?  Is it the config associated with the `lxc remote` command?

If this is no longer of interest to you, then either please let me know here, or just ignore the message and I'll close this bug in approximate 30 days.  Thanks.

**Comment by ajkavanagh** [comment]
Closing due to lack of response.

**Comment by techtonik** [comment]
@ajkavanagh sorry for the late response. It is not actual for me. The point was to automate current manual operations by reusing connection that is already set.

**Comment by ajkavanagh** [comment]
@techtonik The more I think about it, the more I think it's a poor 'fit' for the pylxd library to try to read the default config that a user of lxc has configured for lxc.  I.e. which config should it use, etc.

If you still feel strongly, please could you spec out how you would see it working please?  e.g. how to select the config to use, etc.  Thanks. Alex.

**Comment by techtonik** [comment]
I don't fee strongly about this. I guess there should be function to load current user config "LXD-way". Just because reimplementing config for `pylxd` is tedious task.

**Comment by ajkavanagh** [comment]
Ok, thanks.  I'm going to leave this for now.  Essentially, this is a "load credentials" issue for remote LXD instances (via the local lxd daemon) and until a concrete use case comes up, we won't really know what problem we are trying to solve.

Thanks for bringing it up; it raises awareness of a potential pain point and it means that we'll be more conscious if another similar request is raised.
