### ISSUE TITLE
debianization

### ISSUE THREAD

**Issue by overquota** [lxc/pylxd#236]
Hello! Is there any debianization for pylxd ?
We want to build deb package from it for own private repo. We can write own debianization, but it would be simplier if it is already exists
We already building such deb for lxd from lxd-pkg-ubuntu repo (https://github.com/lxc/lxd-pkg-ubuntu)

**Comment by stgraber** [comment]
pylxd is packaged in Ubuntu, you can get the source package including packaging at https://launchpad.net/ubuntu/+source/pylxd

**Comment by overquota** [comment]
ook, thank you
