### ISSUE TITLE
Is it possible to get resource usage statistics via pylxd?

### ISSUE THREAD

**Issue by nypdmax** [lxc/pylxd#242]
Hello guys,
I am working on some ideas to monitor lxd containers though my own program. Is is possible to get resource usage statistics via pylxd? Or shall I use other libraries? 

Thank you!

**Comment by ajkavanagh** [comment]
@nypdmax I'm not sure, but I'll try to find out.  Are there any particular metrics/stats that you are looking for, or is it a general query?  Thanks.

**Comment by nypdmax** [comment]
Thank you for the reply. Actually we are building a small project using lxd
containers. We hope to find a way to monitor resource usage like CPU,
memory, disk io, network io. So it's more like a general query...now our
solution is installing a small monitor agent in a container which uses
pyutil to get statistics and send them out via UDP packets. Not a beautiful
solution so we would like to see if pylxd can do such things.
Alex Kavanagh <notifications@github.com>于2017年8月17日 周四下午11:05写道：

**Comment by ajkavanagh** [comment]
@nypdmax okay, if you take a look at the [LXD REST-like API](https://github.com/lxc/lxd/blob/master/doc/rest-api.md) there's a method called: [GET /1.0/containers/<name>/state](https://github.com/lxc/lxd/blob/master/doc/rest-api.md#10containersnamestate).

This would be accessed in the pylxd API something like (I've not tested this):

```python
            >>> api = Client().api
            # /
            >>> response = api.get()
            # Check status code and response
            >>> print response.status_code, response.json()
            # /containers/test/state
            >>> print api.containers['test'].state.get().json()
```

Is this useful to you, or were you looking for more details?

**Comment by nypdmax** [comment]
Thank you Alex. That's really helpful, although I'm confused about some
items in the json list. For example, 'cpu usage 158218560186'
means 158218560186 cpu time has elapsed?

**Comment by stgraber** [comment]
CPU time is in nanoseconds (as exposed by the cpuacct cgroup)

**Comment by nypdmax** [comment]
@stgraber Thank you. Does it mean the whole CPU time  elapsed since the last starting time of the container? It's weird as  my container has been running for several days but 158218560186 nanoseconds is almost 159 seconds.

**Comment by stgraber** [comment]
Nope, the counter refers to the amount of CPU time the container's processes actually used. If a container is perfectly idle, the count shouldn't increase at all (obviously near impossible).

**Comment by nypdmax** [comment]
@stgraber @ajkavanagh Thank you all. I think it's time to close this issue.
