### ISSUE TITLE
Recursive push for pushing entire directories

### ISSUE THREAD

**Issue by mrtc0** [lxc/pylxd#246]
I want to do the same thing as `lxc file push -r /path/to container/path/to` .
Is this implementation possible?

**Comment by ajkavanagh** [comment]
@mrtc0 Not exactly.  The recursion available with the lxc command is not implemented in pylxd.  pylxd takes the approach of passing filepath and a string or file handle, and sending this data for one file.  I don't know (offhand) whether this will create the directory.

You should be able to do something like this to create a file:

```python
client.containers['my-container'].files.put(filepath, data)
```

where `data` can be a string or a filehandle.  In the later case, it will stream the file to the filepath.

Unfortunately, currently, we do not have a complete implementation of the `files` part of the API, which is described here: https://github.com/lxc/lxd/blob/master/doc/rest-api.md#10containersnamefiles

**Comment by Samin100** [comment]
I'm having some issues using the put function above. I'm using the default Ubuntu 16.04 container and I'm trying to push an authorized_keys file to the default ubuntu user's .ssh/ directory. Here's the code snippet:

```
# getting the container
container = self.client.containers.get(CONTAINER)
print('container name: {}'.format(container.name))

# pushing some text to the container        
container.files.put(filepath='/home/ubuntu/.ssh/authorized_keys', data='public key goes here!\n')
```

I'm able to put files in the root directory, and even in the /home directory, but for some reason I'm getting this error whenever I try and push anything inside the default ubuntu user's directory, in this case it's `/home/ubuntu/.ssh/authorized_keys`.

``` Traceback (most recent call last):
 File "/home/samin/vectordash/core/ContainerController.py", line 143, in load_container_public_key
    container.files.put(filepath='/home/ubuntu/.ssh/authorized_keys', data='public key goes here!\n')
  File "/usr/local/lib/python3.5/dist-packages/pylxd/models/container.py", line 84, in put
    params={'path': filepath}, data=data)
  File "/usr/local/lib/python3.5/dist-packages/pylxd/client.py", line 115, in post
    self._assert_response(response, allowed_status_codes=(200, 201, 202))
  File "/usr/local/lib/python3.5/dist-packages/pylxd/client.py", line 72, in _assert_response
    raise exceptions.LXDAPIException(response)
pylxd.exceptions.LXDAPIException: file does not exist
```

It seems odd that I would be able to write to the container's `/` and `/root` with no issues, but writing to the ubuntu user's results in an error.

**Comment by Samin100** [comment]
Well...

I fixed the issue. It turns out I was trying to push a file immediately after starting the container - I'm assuming the filesystem might not have been fully loaded. I fixed it with a simple ``time.sleep(3)`` in between a container start and pushing things into the container.
