### ISSUE TITLE
No way of getting command output from container_run_command()

### ISSUE THREAD

**Issue by javacruft** [lxc/pylxd#256]
https://bugs.launchpad.net/ubuntu/+source/python-pylxd/+bug/1544135

There's currently no way of getting command output from container_run_command() currently. You can tell the status of the request to run the command, but not the output of the command itself.

**Comment by smoser** [comment]
container_run_command is in deprecated/api.py
I believe replaced by execute which returns stdout and stderr.

That said, you can't feed input to execute (#244)

**Comment by ajkavanagh** [comment]
This has now been solved (interactively too, with pipelining support) with #321

`container_run_command()` is also deprecated.
