### ISSUE TITLE
Query daemon configuration 

### ISSUE THREAD

**Issue by dann1** [lxc/pylxd#259]
Hello, I'd like to know how to get the output of `lxc config show` with pylxd. I've read the doc but I couldn't find the info.

**Comment by ajkavanagh** [comment]
So, the actual call to get the config is 'GET /1.0' (from https://github.com/lxc/lxd/blob/master/doc/rest-api.md:

e.g. if you do:

```python
import pylxd
c = pylxd.Client()
x = c.get()
x.content
b'{"type":"sync","status":"Success","status_code":200,"operation":"","error_code":0,"error":"" ...
```
This information is provided, preloaded from the JSON, as:

```python
c.host_info
{'api_extensions': ['id_map'],
 'api_status': 'stable',
 'api_version': '1.0',
 'auth': 'trusted',
...
```
