### ISSUE TITLE
Feature: operations websocket

### ISSUE THREAD

**Issue by aarnaud** [lxc/pylxd#26]
Hi,

i will wish use this API : /1.0/operations/<uuid>/websocket

Thanks,

**Comment by uglide** [comment]
:+1:

**Comment by tych0** [comment]
On Wed, Aug 26, 2015 at 07:53:47AM -0700, Anthony Arnaud wrote:
> Hi,
> 
> i will wish use this API : /1.0/operations/<uuid>/websocket

Isn't this implemented by operation_stream()?

**Comment by uglide** [comment]
@tych0 It's not implemented by operation_stream(). [get_ws() function in connection module is not implemented properly](https://github.com/lxc/pylxd/blob/master/pylxd/connection.py#L130-L134)

Current implementation returns only status code instead of web socket object.

**Comment by uglide** [comment]
This issue should be closed because appropriate pull request was merged (#41)
