### ISSUE TITLE
Image creation from container is undocumented

### ISSUE THREAD

**Issue by duk3luk3** [lxc/pylxd#263]
Is it correct that there is no implementation for creating an image from a container, as in the "source container" case described here: https://github.com/lxc/lxd/blob/master/doc/rest-api.md#post-7 ?

**Comment by ajkavanagh** [comment]
Yes, there is no mechanism currently to provide that functionality as far as I can tell.  It would most likely be added into `class Image(model.Model)` in `pylxd/pylxd/models/image.py` at, or around, https://github.com/lxc/pylxd/blob/master/pylxd/models/image.py#L177.

**Comment by duk3luk3** [comment]
Thank you, that confirms what I thought. I will work on it if I find time.

**Comment by duk3luk3** [comment]
It turns out `container` has a `publish` method:

https://github.com/lxc/pylxd/blob/0722955260a6557e6d2ffde1896bfe0707bbca27/pylxd/models/container.py#L299-L321

It's missing from the docs though: https://pylxd.readthedocs.io/en/latest/containers.html#container-methods
