### ISSUE TITLE
request: new pypi release for snap support

### ISSUE THREAD

**Issue by powersj** [lxc/pylxd#264]
Using pylxd 2.2.4 with lxd 2.21 installed a snap, creating a client fails:
https://paste.ubuntu.com/26328736/

It looks like in tree there are now checks for lxd as a snap and for the unix.socket under /var/snap. Can another release get published to enable the use of these fixes?

**Comment by duk3luk3** [comment]
If you are installing pylxd from pypi and not from a distro package, you should also be able to install it using `pip install git+https://github.com/lxc/pylxd.git` as a workaround. (See pip documentation: [pip VCS Git](https://pip.pypa.io/en/stable/reference/pip_install/#git))

**Comment by powersj** [comment]
@duk3luk3 thanks for the suggestion! I was not aware that you could checkout a specific hash. We have gone ahead and used that instead. Thanks again!

**Comment by ajkavanagh** [comment]
We'll be rolling a new release soon, but yes, as @duk3luk3 points how, pip is very flexible in where you can get your package from.
