### ISSUE TITLE
execute returns stdout, stderr as strings, and silently fails if output is not utf-8.

### ISSUE THREAD

**Issue by smoser** [lxc/pylxd#268]
The result of a command execution is currently being decoded into a utf-8 string.  This is presumably so it can be json serialized.  Not all command output is utf-8, and should not be expected to be so.

The failure path currently warns and then returns an empty string instead.  As seen below, the exit code of the command does seem to get preserved, but if stdout or stderr had non-utf8 characters, they are returned as empty strings.

        >>> from pylxd import Client
        >>> c = Client()
        >>> container = c.containers.all()[0]
        >>> r = container.execute(['printf', '\\xff'])
        Terminating websocket [Bound to ''] due to exception: UnicodeDecodeError('utf-8', b'\xff', 0, 1, 'invalid start byte') in once method
        >>> r = container.execute(['bash', '-c', 'printf "$0"; exit 1;', '\\xff'])
        Terminating websocket [Bound to ''] due to exception: UnicodeDecodeError('utf-8', b'\xff', 0, 1, 'invalid start byte') in once method
        >>> r
        ContainerExecuteResult(exit_code=1, stdout='', stderr='')

**Comment by ajkavanagh** [comment]
So the relevant line of code is https://github.com/lxc/pylxd/blob/master/pylxd/models/container.py#L356 from:

```python
    def received_message(self, message):
        if len(message.data) == 0:
            self.close()
            self.manager.remove(self)
        if message.encoding:
            self.buffer.append(message.data.decode(message.encoding))
        else:
            self.buffer.append(message.data.decode('utf-8'))
```

We have to decode it to something (as it's a Py3 compatible library) if we want to return a `str`, and the message returned from the `ws4py` library which has a default encoded of 'utf-8' (see https://github.com/Lawouach/WebSocket-for-Python/blob/master/ws4py/messaging.py#L13):

```python
class Message(object):
    def __init__(self, opcode, data=b'', encoding='utf-8'):
        """
...
```

So the question is: "What encoding should we try?"   There's a couple of strategies that could be used:

1. Try utf-8, see what happens, and if it fails, try ascii.
2. Allow the user of the `pylxd` to specify what encoding to use, somehow, but with a default of 'utf-8' to match the underlying library.

I'm erring towards changing the signature of `execute` to:

```python
    def execute(self, commands, environment={}, encoding='utf-8'):
```

Thoughts?

**Comment by smoser** [comment]
Why do you think you have to  / should return a string?  Just for backwards compatibility?
For comparision, consider [check_output](https://docs.python.org/3/library/subprocess.html#subprocess.check_output) which returns bytes.  The simple fact is that command output is bytes ('dd if=/dev/urandom bs=10 count=1') that sometimes (most of the time) can be decoded as utf-8.

For backwards compatibility I would suggest changing the signature to:

    def execute(self, commands, ..., decode=True)

Then if decode is False you return bytes.  If True, you return <bytes>.decode(utf-8).  If someone wants that decoded as anything else, then they can easily decode themselves.

We went through this same basic path with our subprocess wrapper 'subp' in cloud-init and curtin.  Its signature is more complex because we tried to support decoding for the caller.  I think its just easy enough to return either bytes or <bytes>.decode('utf-8').

If you do want to go down the encoding='utf-8' parameter path, then just please make sure that you support explicit "do not decode" value such as decode=None.

**Comment by ajkavanagh** [comment]
> Why do you think you have to / should return a string? Just for backwards compatibility?
For comparision, consider check_output which returns bytes. The simple fact is that command output is bytes ('dd if=/dev/urandom bs=10 count=1') that sometimes (most of the time) can be decoded as utf-8.

Yes, basically for backwards compatibility.  I don't want to break existing clients that are expecting strings and then suddenly get bytes.

I suspect that`execute(...)`  should have been the same as `subprocess.run(...)` and friends, which have an `encoding` parameter, and it defaults to `None`.  However, we are where we are.

I do. however, totally agree on the need to able to **not** do any decoding, and just return the raw buffer back.  So an `encoding=None` call param that doesn't try to decode is a great idea.  Thanks.

**Comment by ajkavanagh** [comment]
PR #291 provides the fix for this.
