### ISSUE TITLE
pylxd fails to correctly identify existing profiles.

### ISSUE THREAD

**Issue by snesbittsea** [lxc/pylxd#282]
This is with Python 2.7 and pylxd 2.2.5 and lxc version 2.21

I'm running into a situation where pylxd successfully gets a list of all my profiles, but then fails to recognize some of them as existing.

The script below simply iterates through the listing of profiles and then asks if that profile exists:

```python
from pylxd import Client
from pylxd.models import Profile

import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

client = Client(endpoint='blanked out',
                 cert=("/home/FUZZBUTT/snesbitt/snap/lxd/5758/.config/lxc/client.crt",
                       "/home/FUZZBUTT/snesbitt/snap/lxd/5758/.config/lxc/client.key"),
                verify=False)
client.authenticate('blanked out')

for profile in Profile.all(client):
    print("Profile Name: %s. Exists: %s" % (profile.name, Profile.exists(client, profile.name)))
```

The result of this script is:

```
/home/FUZZBUTT/snesbitt/projects/ansible/venv_2.7/bin/python2 /home/FUZZBUTT/snesbitt/.IntelliJIdea2018.1/config/scratches/scratch.py

/home/FUZZBUTT/snesbitt/projects/ansible/venv_2.7/bin/python2 /home/FUZZBUTT/snesbitt/.IntelliJIdea2018.1/config/scratches/scratch.py
Profile Name: default. Exists: True
Profile Name: devAnsibleServer. Exists: True
Profile Name: dev. Exists: True
Profile Name: maas. Exists: True
Profile Name: tmpl_consulserver. Exists: False
Profile Name: test-test. Exists: True
Profile Name: test_test. Exists: True
Profile Name: test_testtesttest. Exists: True
Profile Name: test-testtesttest. Exists: True
Profile Name: tmpl_consulserver1. Exists: True
Profile Name: tmpl-consulserver1. Exists: True
```

Note that pylxd marks tmpl_consulserver as not existing.

I'm also noting that the output is a bit flaky and the results can change after adding a new profile. The one constant is that tmpl_consulserver is always marked as not existing.

(*edit:ajkavanagh just fixed up formatting*)

**Comment by ajkavanagh** [comment]
Well that's a bit strange.  It might be a bug in the underlying LXD implementation; before I 'blame' them, is there anything different, say, between the profiles of `tmpl_consulserver` and the other variants (with `-` and `_.*1`) for example?  i.e. please could you past the contents of those profiles.

The "reason" exists comes back as `False` is if a `NotFound` exception is raised via the API handling, which would imply a 404 from the LXD daemon.  Which as you say, is a bit strange and flaky.

Thanks.

**Comment by snesbittsea** [comment]
Sorry about the late reply and poor original formatting.

Naturally my test fixture for this was deleted as part of ongoing work, and I can't recreate <sigh>

Let's close for now.

**Comment by ajkavanagh** [comment]
Okay, thanks for letting me know.  I'll close it for now, but please feel free to re-open it if you come across it again.  The module's tests with sockets isn't very complete at the moment; it's something that I'm working on, as there seem to be a few bugs/issues arising with TCP/IP & web-sockets, whereas most of my testing is with the local unix sockets.
