### ISSUE TITLE
NotFound is raised when trying to access the stateful property of the container snapshot. pylxd 2.2.6 

### ISSUE THREAD

**Issue by Silentphantom62** [lxc/pylxd#295]
After upgrading to pylxd 2.2.6 while accessing the stateful property of the container snapshot object, NotFound error is thrown.

LXC version: 3.0.0

```
from pylxd import Client
client = Client()
container = client.containers.get('test')
snapshots = container.snapshots.all()
print(snapshots[0].name)
print(snapshots[0].stateful)
```

```
web_1  | Traceback (most recent call last):
web_1  |     print(snapshots[0].stateful)
web_1  |   File "/usr/local/lib/python2.7/dist-packages/pylxd/models/_model.py", line 125, in __getattribute__
web_1  |     self.sync()
web_1  |   File "/usr/local/lib/python2.7/dist-packages/pylxd/models/_model.py", line 154, in sync
web_1  |     response = self.api.get()
web_1  |   File "/usr/local/lib/python2.7/dist-packages/pylxd/client.py", line 125, in get
web_1  |     self._assert_response(response, stream=kwargs.get('stream', False))
web_1  |   File "/usr/local/lib/python2.7/dist-packages/pylxd/client.py", line 90, in _assert_response
web_1  |     raise exceptions.NotFound(response)
```

**Comment by ajkavanagh** [comment]
Hi @Silentphantom62.  I've tried to reproduce it with my 2.2.6 and lxc 2.0.11, and I've not been able to.  Please could you update the bug report with your lxc version too?

This is my attempt at reproducing (I created a test container and did a single snapshot on it).

    In [1]: from pylxd import Client
       ...: client = Client()
       ...: container = client.containers.get('test')
       ...: snapshots = container.snapshots.all()
       ...: print(snapshots[0].name)
       ...: print(snapshots[0].stateful)
       ...: 
    snap0
    False

Thanks.

**Comment by Silentphantom62** [comment]
@ajkavanagh updated the LXC version in the bug report. Please let me know if you need anything else.

**Comment by Silentphantom62** [comment]
Hope this helps. @ajkavanagh 

```
pylxd 2.2.4 and lxc 3.0.0/ lxc 2.21 = Works

pylxd 2.2.6 and lxc3.0.0/ lxc 2.21 = Breaks.
```

**Comment by ajkavanagh** [comment]
@Silentphantom62 ah, 3.0.0 is really hot off the presses (released March 30).  It's not supposed to have changed that much, from an API perspective, but I'm guessing something has changed.  I'll try and reproduce it.

**Comment by ajkavanagh** [comment]
Okay, I've not managed to reproduce it.  I'm not sure if lxd 3.0.0 is supposed to 'work' with lxc < 3.0.0, but obviously some combinations do.

I have a working set up with lxd 3.0.0, lxc 3.0.0 and pylxd 2.2.6.

i.e. I'm using the snap version of lxd and it uses lxc 3.0.0 and pylxd 2.2.6 works with that.

How are you installing lxd and lxc? (i.e. where do the versions come from?) Please could you post your results of:

    which lxc
    which lxd
    lsb_release -d

Thanks.

**Comment by Silentphantom62** [comment]
Sorry If I wasn't clear. I have 2 hosts one with lxc and lxd 3.0.0 and the other with lxc and lxd 2.21.

$ which lxc
/snap/bin/lxc

$ which lxd
/snap/bin/lxd

$ lsb_release -d
Description:	Ubuntu 16.04.4 LTS

**Comment by Silentphantom62** [comment]
The apt packages for LXD ended at 2.21, so we had to migrate to snap to upgrade to 3.0.0. Is this info of any assistance?

**Comment by Silentphantom62** [comment]
@ajkavanagh I think I know how to reproduce this now. Try creating a snapshot with an "_" in the name of the snapshot.

`snapshot = container.snapshots.create('my_snapshot', stateful=False, wait=True)`

**Comment by ajkavanagh** [comment]
@Silentphantom62 ah, interesting;  okay, I'll take a look at that and see what I can find.

**Comment by ajkavanagh** [comment]
So, the bug is due to this: https://github.com/lxc/pylxd/blame/2.2.6/pylxd/client.py#L73

When storage pools were added, the `__getitem__(...)` method on API method has been erroneously updated to cover `api...storage_pool..` where as this breaks `api...snapshots[name]`.

I'll have a ponder on the right way to fix this; I might just special case `storage_pool`  on `__getattr__()` and drop it from `__getitem__(...)` altogether.  I don't *think* this will cause a problem.

**Comment by ajkavanagh** [comment]
Re-opening until we release this in a version.

**Comment by Silentphantom62** [comment]
@ajkavanagh Thanks!
