### ISSUE TITLE
InsecureRequestWarning with Certs

### ISSUE THREAD

**Issue by ilhaan** [lxc/pylxd#312]
I'm using `pylxd` version 2.2.7 & `lxd` version 3.1. I'm confused about the use of certificates for client authentication as outlined [here](https://pylxd.readthedocs.io/en/latest/authentication.html#). I added a certificate for my remote machine (`192.168.1.2`) on my local machine (`192.168.1.1`) by running the following on the remote: 
```
lxc config set core.https_address [::]:8443
lxc config set core.trust_password <something-secure>
```
I verified that my local machine was listed as a trusted client by running `lxc config trust list`. Since I have a `snap install` of `lxd` on my machine, I found my `client.crt` and `client.key` files in `/home/user/snap/lxd/7412/.config/lxc`. I then tried to use these using `pylxd` as shown below: 

```
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pylxd import Client 
>>> client = Client(endpoint='https://192.168.1.2:8443', cert=('/home/user/snap/lxd/7412/.config/lxc/client.crt', '/home/user/snap/lxd/7412/.config/lxc/client.key'), verify=False)
/home/user/.virtualenvs/test/lib/python3.5/site-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
>>> client.cert
('/home/user/snap/lxd/7412/.config/lxc/client.crt', '/home/user/snap/lxd/7412/.config/lxc/client.key')
>>> client.trusted
True
```
It can be seen above that `pylxd` is able to successfully connect to the remote and authenticate, however a `InsecureRequestWarning` warning is shown. My questions: 

1. Have I not used the certificate and key correctly? As per [this](https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings), `InsecureRequestWarning` is a result of making a request to an HTTPS URL without certificate verification. Is that not what was done here?
2. I did not generate the certificate and key used above and used the ones generated by `lxd`. Should I be generating these using `openssl` myself or is it ok to use the `lxd` generated ones? 
3. If this is expected behavior, how do I suppress this warning? (I am running this on an internal network and not concerned about eavesdropping).

**Comment by ilhaan** [comment]
Ok, I will look into setting up the server using a PKI based setup. Will wait to hear from you regarding your testing.

**Comment by ilhaan** [comment]
For anyone looking to suppress the urllib3 warnings, you can include the following: 
```
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
```
More info on this [here](https://github.com/influxdata/influxdb-python/issues/240)

**Comment by ajkavanagh** [comment]
@ilhaan thanks!  Very useful info.  I'd rather the user had to deliberately suppress the warnings than do it automatically in the library.  I'm going to close this, as it's working as designed.
