### ISSUE TITLE
pylxd 2.2.7 with lxd >= 3.0.1: execute method doesn't terminate for a long time.

### ISSUE THREAD

**Issue by ajkavanagh** [lxc/pylxd#316]
Essentially, this is probably due to the work-around for the socket code to stop the `NotFound` issue (#280) which worked brilliantly for lxd 2.x, but something seems to have changed in lxd 3.x.  Main issues are:

 * Xenial + lxd 2.0.11 -- no delays at all
 * Xenial + lxd 3.2 (snap) -- long delays
 * Bionic + lxd 3.0.1 -- long, long, long delays
 * Bionic + lxd 3.2 (snap) -- long delays

Test code (from @marcogh) which shows the error is:

```python
import logging
logging.basicConfig(level=logging.DEBUG)
import pylxd
client = pylxd.Client()
config = {'name': 'c2', 'source': {'type': 'image', "mode": "pull", "server":
    "https://cloud-images.ubuntu.com/daily", "protocol": "simplestreams", 'alias': 'bionic/amd64'}}
container = client.containers.create(config, wait=True)
container.status
container.start(wait=True)
container.status
container.execute(['ls','/'])
```

pylxd 2.2.6 run (which is fast and works -- apart from long running execs ...)

```
DEBUG:urllib3.connectionpool:http://localhost:None "POST /1.0/containers/c2/exec HTTP/1.1" 202 796
INFO:ws4py:Using epoll
INFO:ws4py:Managing websocket [Bound to '']
INFO:ws4py:Managing websocket [Bound to '']
INFO:ws4py:Removing websocket [Bound to '']
INFO:ws4py:Removing websocket [Bound to '']
DEBUG:urllib3.connectionpool:http://localhost:None "GET /1.0/operations/e99c59dc-178d-4696-a2d0-5584eeff57cb HTTP/1.1" 200 446
```

pylxd 2.2.7 which hangs waiting for the websocket to terminate:
```
DEBUG:urllib3.connectionpool:http://localhost:None "POST /1.0/containers/c2/exec HTTP/1.1" 202 796
INFO:ws4py:Using epoll
INFO:ws4py:Managing websocket [Bound to '']
INFO:ws4py:Managing websocket [Bound to '']
DEBUG:urllib3.connectionpool:http://localhost:None "GET /1.0/operations/26a0cce1-5060-4e7f-aec4-4a290c9c17f2 HTTP/1.1" 200 733
DEBUG:urllib3.connectionpool:http://localhost:None "GET /1.0/operations/26a0cce1-5060-4e7f-aec4-4a290c9c17f2 HTTP/1.1" 200 446
INFO:ws4py:Terminating websocket [Bound to '']
INFO:ws4py:Terminating websocket [Bound to '']
```

I'll do some digging, but it's almost certainly a socket not completing or similar.

**Comment by Silentphantom62** [comment]
Hey @ajkavanagh even I am facing the issue with pylxd 2.2.7 and LXD 3.0.1, all the execute methods are hanging for a really long time.
Can we please get a fix for this asap? Please let me know if you need any further details to help you fix this.

**Comment by ajkavanagh** [comment]
@Silentphantom62 unfortunately I'm travelling all day today with intermittent data connections, so it's a bit tricky for me to look at this (plus I'm then on holiday/away from my computer for the rest of the week).  I will take a look at this when I can.  The relevant code is in `models/container.py` around line 395 in the `execute(...)` method.  I'll set something up with some debug to see what's going on, but if anyone can take a look at that bit of code and see any obvious errors, that would be great!

**Comment by Silentphantom62** [comment]
There might be some timeout until which the websockets are left open(120 seconds).
Delay between the Managing websocket's log message and Terminating websocket log message is 120 seconds(see LOG). Which is because of the below lines.

`            while len(manager.websockets.values()) > 0:
                time.sleep(.1)  # pragma: no cover`

Since we are already waiting for the end of the command in the code above this, maybe get rid of this and let manager.stop() handle releasing the sockets?

LOG: 
`INFO 2018-07-11 22:26:10,395 manager 8796 123145566584832 Managing websocket [Local => <ip_address>:<port> | Remote => <ip_address>:<port>]
INFO 2018-07-11 22:26:10,438 manager 8796 123145566584832 Managing websocket [Local => <ip_address>:<port> | Remote => <ip_address>:<port>]
INFO 2018-07-11 22:28:11,343 manager 8796 123145572401152 Terminating websocket [Local => <ip_address>:<port> | Remote => <ip_address>:<port>]
INFO 2018-07-11 22:28:11,347 manager 8796 123145572401152 Terminating websocket [Local => <ip_address>:<port> | Remote => <ip_address>:<port>]`

**Comment by Silentphantom62** [comment]
@ajkavanagh Any thoughts on this? This is a critical piece.

**Comment by lasizoillo** [comment]
@Silentphantom62 sorry, it was my fault. I worked on an old branch. Now maybe need some changes to api. I'm not very happy with stdin parameter names [see here](https://github.com/lxc/pylxd/pull/321/commits/b5feaceae8f29bf8b7ec6bc52653c45d349ebd8e#diff-91bfca6ea20e77c7f14290044515deabR340)

Maybe need be renamed or redo to work only with binary file like input streams and simplify unicode manipulations. What do you think?

Yes, I know that your are naming critical piece very long time in execute function. For me no stdin and delayed stdout/stderr outputs are critical too. I'll hope this patch resolve our issues ;-)

**Comment by Silentphantom62** [comment]
@lasizoillo I think your approach of making it clean by just allowing binary streams and simplifying unicode manipulations is a good way to go ahead for now.
