### ISSUE TITLE
is there a way to use pylxd.client talk to specific api url directly, like we use requests?

### ISSUE THREAD

**Issue by pan87232494** [lxc/pylxd#325]
is there a way to use client.api  to send GET request to cluster host within pylxd  client.
such as:
send GET to https://127.0.0.1:8443/1.0/cluster/members,  then we will have 3.0 api response directly.

**Comment by ajkavanagh** [comment]
Unfortunately, clustering is not yet supported in the pylxd API.  Please see #292.

Unfortunately, the API is not flexible enough to enable arbitrary endpoints to be accessed, although that is something that I'm considering with a new major version (but I've only got a proposal for that at present: #283.
