### ISSUE TITLE
client.events() call should support filtering the event types 

### ISSUE THREAD

**Issue by moysesb** [lxc/pylxd#332]
Context: I'm trying to put together something like gliderlab's [registrator](https://github.com/gliderlabs/registrator), using lxc containers instead of Docker. I need to receive a stream of lifecycle notifications from lxd so I can register/de-register the containers with Consul as they come and go.

Currently, a pylxd event subscription is all-or-nothing; I would like to be able to pass on the query argument ```type``` supported by lxd's rest api at the /1.0/events endpoint so I can receive only the container lifecyle events without wasting resources with other event types like logging.

I might be able to open a PR with an implementation of this feature in the next few days if that's ok.

**Comment by ajkavanagh** [comment]
Fixed by #341.
