### ISSUE TITLE
2.2.8 - Container.execute() still waits for 120 seconds in some cases.

### ISSUE THREAD

**Issue by Silentphantom62** [lxc/pylxd#336]
pylxd = 2.2.8
lxd = 3.0.2

**Steps to reproduce:**
1. Create a centos 7 container.
`lxc launch images:centos/7/amd64 my-container`

2. Run the following
```
import time

from pylxd import Client

client = Client(endpoint='https://<lxd-host>:<port>',
                verify=False, cert=('mylxd.crt', 'mylxd.key'))
client.authenticate('secret')
assert client.trusted

container = client.containers.get('my-container')

print("Started executing command -> Time:{0}".format(time.strftime('%X %x %Z')))
resp = container.execute(['useradd', '-m', 'centos', '-s', '/bin/bash'])
print("Done -> Time:{0}".format(time.strftime('%X %x %Z')))
print(resp.stdout, resp.stderr, resp.exit_code)
```

**Output:**
```
Started executing command -> Time:14:01:07 11/09/18 PST

Done -> Time:14:03:07 11/09/18 PST

(u'', u"useradd: user 'centos' already exists\n", 9)
```

**Comment by Silentphantom62** [comment]
Looks like the execution is stuck in this loop waiting for all sockets to be closed.
https://github.com/lxc/pylxd/blob/master/pylxd/models/container.py#L417

**Comment by Silentphantom62** [comment]
@ajkavanagh Did you get a chance to look at this?

**Comment by lasizoillo** [comment]
Hi, I've created a pull request #337 to workaround the bug in ws4py. Sorry for the delay, but I've no time this days to work in it before.

**Comment by ajkavanagh** [comment]
@lasizoillo hey no worries, we're all very busy!  Thanks for doing the detective work on this.  I'll do some testing with the patch today with the @Silentphantom62 use case, and if all is good, merge the patch and release 2.2.9.  Even if it's not a complete fix, it'll obviously be a step in the right direction.  Thanks again.

**Comment by ajkavanagh** [comment]
So, I've done a bunch of testing with #337, which I'm going to merge.  @Silentphantom62 if you could also have a go at testing #337 that would be good.

**Comment by ajkavanagh** [comment]
@Silentphantom62 does the fix in #337 fix the issue for you?

**Comment by ajkavanagh** [comment]
Closing this issue as I believe #337 has fixed it.  Please re-open it if you think it's still an issue.  Thanks.

**Comment by Silentphantom62** [comment]
@ajkavanagh This seems to fix the issue, at least for now. Will re-open if I see it again.
Can we release 2.2.9 with this fix?
