### ISSUE TITLE
cloudconfig data

### ISSUE THREAD

**Issue by BryanQuigley** [lxc/pylxd#340]
Am I doing something obviously wrong here?  

import pylxd
client = pylxd.Client()
container_name = "sp-setup"
user_vendor_data = '''#cloud-config\nruncmd:\n   - [mkdir, /home/ubuntu/workdir]#\n\n'''
config = {'name': container_name, 'source': {'type': 'image', "mode": "pull", "server":
    "https://cloud-images.ubuntu.com/daily", "protocol": "simplestreams", 'alias': 'bionic/amd64'}, 'user.vendor-data': user_vendor_data}
container = client.containers.create(config, wait=True)
container.start()

The vendor data never makes it to the image.

**Comment by BryanQuigley** [comment]
actually I think I can get by with the workaround in #244

**Comment by ajkavanagh** [comment]
AFAICT that's part of the profile data for the container.  So the usual dance would be to set up the profile and add that key to the profile, and then use the profile in the container create command.

e.g.
```python
        config = {
            ...
            "user.vendor-data": "..."
        }
        profile client.profiles.create("my-new-profile", config, devices)

        container_config = {
            'name': somename,
            'profiles': ["my-new-profile"],
            'source': {
                'type': 'image',
                'alias': some-image-ref,
            },
        }
        container = self.client.containers.create(
            container_config, wait=True)
```
