### ISSUE TITLE
pylxd suddenly changes default endpoint

### ISSUE THREAD

**Issue by jvrsantacruz** [lxc/pylxd#346]
Hi all :)

The pylxd Client suddenly changes the default endpoint when a second server is installed via snap.

It stops looking to `/var/lib/lxd/unix.socket` in favour of `/var/snap/lxd/common/lxd/unix.socket`.
This is problematic as it suddenly and unexpectedly changes the server, breaking the current configuration.
It was introduced by 4f7056bfbe10916fc4109225d0cc38cf92a90e3f probably for the convenience of personal setups.

The default endpoint had to be forced for all applications using pylxd with the equivalent of the code below, to make sure that both the `lxd` command line tool and the client point to the same default and won't change without user consent when installing a parallel version just to test.

```python
import os
import pylxd

os.environ.setdefault('LXD_DIR', '/var/lib/lxd')
client = pylxd.Client()
```

We think that `/var/snap/lxd/common/lxd/unix.socket` should not take precedence over the default location.
It's prone to error, as calling the client with default arguments will then go to a completely different place.
The default `lxc` command line tool does not exhibit this behaviour. When used along, they will confusingly point to a different lxd server.
If someone installs an alternative version of lxd, it should be configured explicitly and not to take over the one it's being used without a warning. If the alternative version wants to become the default without config, it should symlink the socket to become so.

Thanks!!

**Comment by ajkavanagh** [comment]
The pylxd client does look to see if the snap unix socket endpoint is installed and defaults to that.  I wasn't aware that the lxc client defaults to the non-snap installed version, so, yes, that *is* an inconsistency that should be fixed.

However, the pylxd client still needs to work in a snap only installed environment, and thus needs to search for the snap endpoint version.  It may be that the priority needs to be switched.

It's *odd* that a server would have a package *and* snap installed lxd at the same time.  The procedure for installing the lxd snap is to do:

```bash
sudo snap install lxd
sudo lxd.migrate
```

This moves everything to the snap version of lxd, and then (by default) *removes* the package install version. May I ask why you are running both on the same machine at the same time?

**Comment by jvrsantacruz** [comment]
Hi,

Thanks @ajkavanagh for the prompt response.

Yes, there are more than one lxd server in the same machine. Sometimes people keep several instances of the lxd server running at the same time; the apt installed version along with the snap ones, usually testing the differences to ensure lxd-based apps will work on different versions.

**Comment by ajkavanagh** [comment]
Hi @jvrsantacruz 

I'm just circling back to this one.  It looks like the _intent_ of the lxd team is that _either_ the apt package version is install _or_ the snap version is installed.  I just set up a fresh bionic instance, set up lxd (package version) and created a container. _Then_ I installed the snap version.  When I try to run the snap lxd version of init it complains:

```
$ sudo /snap/bin/lxd init
Error: Both native and snap packages are installed on this system
       Run "lxd.migrate" to complete your migration to the snap package
```

Although I _might_ be able to get them working, I don't think that is the intent.  Therefore, I'm going to close this bug, as it only occurs if both are installed, and I don't think this is a supported configuration.

Please feel free to add comments against this viewpoint, as you may still want this functionality; in which case we can try to work out the best way of doing it
