### ISSUE TITLE
Support for restore snapshots

### ISSUE THREAD

**Issue by Miso-K** [lxc/pylxd#353]
Is there any direct option for restore snapshots ? 
It will be great to have some function for this eg. restore( SNAPSHOT_NAME )
I found that it is possible to do by using only raw_put:
` vps1.raw_put( { 'restore': 'test2' } ) `

**Comment by ajkavanagh** [comment]
Yup, this looks like a missing feature.  Thank you for high-lighting it.  We'd need to add that to the container methods.

As you've discovered, I added the `raw_*` functions to help cope with this kind of issue; you can access *any* part of the API using `raw_*` functions if you need them, but we should definitely add this feature, as it's a bit inconvenient to force people to use raw functionality!
