### ISSUE TITLE
Release 2.2.9

### ISSUE THREAD

**Issue by Silentphantom62** [lxc/pylxd#354]
@ajkavanagh Can we release 2.2.9 with the fix #337 ? It's a critical fix and it would be great to have this released ASAP.

**Comment by Silentphantom62** [comment]
@ajkavanagh what do you think?

**Comment by ajkavanagh** [comment]
Yup, I'll release a new version tomorrow.  All testing with the current version has gone well.

**Comment by Silentphantom62** [comment]
Thanks, @ajkavanagh! Looking forward for the release.

**Comment by ajkavanagh** [comment]
2.2.9 is released.  Thanks to everybody who contributed.
