### ISSUE TITLE
Make something about `python -m pylxd`

### ISSUE THREAD

**Issue by techtonik** [lxc/pylxd#36]
Would be nice to have something like diagnostic info when executed standalone. Maybe some commands.
```
$ python -m pylxd
...
No module named pylxd.__main__; 'pylxd' is a package and cannot be directly executed
```

I personally think to try `pylxd` for controlling remote container, so inspecting if `pyxld` can connect it from command line would be nice.

**Comment by rockstar** [comment]
I think this is beyond the scope of the current usage of pylxd. I would gladly review a patch that performed this functionality, should you have a use case, but as the current developers don't have a use case, we won't be focusing on writing this code.
