### ISSUE TITLE
container.execute long running command stdout only returns start of output

### ISSUE THREAD

**Issue by kimfaint** [lxc/pylxd#362]
It seems when a command takes a while to run, the stdout only returns the first part of the output.  If I use subprocess to run the same command via the `lxc` cli, then I get the full output.  For example:

```python
#!/usr/bin/env python

from pylxd import Client
import subprocess
import time

#args = ['ls', '-la']
args = ['ping', '-c', '4', 'localhost']

client = Client()
print('Create container')
#config = {'name': 'apphost', 'source': {'type': 'image', 'fingerprint': '012d2462c11a'}} #centos/7
config = {'name': 'apphost', 'source': {'type': 'image', 'fingerprint': '31235ca07a33'}} #ubuntu/18.04
container = client.containers.create(config, wait=True)
print('Start container')
container.start(wait=True)
print('==========\npylxd container.execute')
(code, stdout, stderr) = container.execute(args, environment={'LANG': 'en_AU.UTF-8'})
print('code:', code)
print('stdout:', stdout)
print('stderr:', stderr)
print('==========\nsubprocess.run')
proc = subprocess.run(['lxc', 'exec', 'apphost', '--env', 'LANG=en_AU.UTF-8', '--'] + args,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
)
print('code:', proc.returncode)
print('stdout:', proc.stdout.decode())
print('stderr:', proc.stderr.decode())
container.stop(wait=True)
container.delete()
```
output:
```
Create container                            
Start container                                                                      
==========          
pylxd container.execute 
code: 0                 
stdout: PING localhost(localhost (::1)) 56 data bytes
64 bytes from localhost (::1): icmp_seq=1 ttl=64 time=0.015 ms                             
                               
stderr:                        
==========
subprocess.run                 
code: 0                               
stdout: PING localhost(localhost (::1)) 56 data bytes
64 bytes from localhost (::1): icmp_seq=1 ttl=64 time=0.014 ms
64 bytes from localhost (::1): icmp_seq=2 ttl=64 time=0.034 ms
64 bytes from localhost (::1): icmp_seq=3 ttl=64 time=0.047 ms
64 bytes from localhost (::1): icmp_seq=4 ttl=64 time=0.034 ms
      
--- localhost ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3049ms
rtt min/avg/max/mdev = 0.014/0.032/0.047/0.012 ms
                                               
stderr:                                         
```

For quick commands like `ls -la /` the full output is returned.

Environment:
- Ubuntu 18.04.2
- Python 3.6.7
- lxd 3.0.3

Pip installed:
- pylxd (2.2.9)
- ws4py (0.5.1)

**Comment by ajkavanagh** [comment]
Yes, I've confirmed this with the snap version of lxd as well (currently 3.12).  Therefore, it's likely to be the handling of the stdout/stderr and the websocket library in pylxd.  This has been a right pain to get right.  I suspect that the command is 'finishing' before the buffer is flushed, or we're still not handling the websocket correctly, thus missing the bulk of the output.

**Comment by ajkavanagh** [comment]
@kimfaint Hi, I found the error and fixed it. It took a bit of testing (and staring at the lxd go client code) to work out what was going on.  This version seems to work, but there's a possibility that very slow network connections might mix up the reception of various packets and miss stdout or stderr data.  Actually doing it 'properly' and waiting for the close from the LXD server daemon adds a 30-60 seconds wait to the end of the message.  LXD sends an empty string to indicate the end of it's stream, and we look for that.

Anyway, this is much better than it was.  If you can test from master that would be great, and then I'll see to get a new version released on PyPi as this is a pretty bad error!  Thanks.

**Comment by kimfaint** [comment]
Legend! Thanks. I'll pull master today, give it a spin with my use cases and report back.

**Comment by ajkavanagh** [comment]
@kimfaint Great, there was a tiny regression (#364) but that's now been merged.

**Comment by kimfaint** [comment]
@ajkavanagh I've confirmed with pylxd 2.2.10.dev17 that execute is working with my use cases.

**Comment by ajkavanagh** [comment]
@kimfaint great stuff; I'll get a release sorted out. Thanks.
