### ISSUE TITLE
AttributeError: 'StoragePool' object has no attribute 'volumes'

### ISSUE THREAD

**Issue by AceSlash** [lxc/pylxd#368]
On LXD version 3.14 from snap on Ubuntu 18.04.02 , using the python3 version installed via `apt install python3-pylxd`, when I'm trying to follow the example of the documentation from https://pylxd.readthedocs.io/en/latest/storage-pools.html , this is what I get:
```
# python3
Python 3.6.8 (default, Jan 14 2019, 11:02:34)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pylxd import Client
>>> client = Client()
>>> storage_pool = client.storage_pools.get('default')
/usr/lib/python3/dist-packages/pylxd/models/_model.py:116: UserWarning: Attempted to set unknown attribute "status" on instance of "StoragePool"
  key, self.__class__.__name__
/usr/lib/python3/dist-packages/pylxd/models/_model.py:116: UserWarning: Attempted to set unknown attribute "locations" on instance of "StoragePool"
  key, self.__class__.__name__
>>> storage_pool = client.storage_pools.get('default')
>>> volumes = storage_pool.volumes.all()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/pylxd/models/_model.py", line 122, in __getattribute__
    return super(Model, self).__getattribute__(name)
AttributeError: 'StoragePool' object has no attribute 'volumes'
>>> 
```

For reference, the doc example is currently:
```
storage_pool = client.storage_pools.get('pool1')
volumes = storage_pool.volumes.all()
named_volume = storage_pool.volumes.get('custom', 'vol1')
```

**Comment by ajkavanagh** [comment]
Hi, that's very odd.  Please could you print the output of `pylxd.__version__`, where pylxd is the imported pylxd.  Thanks.

**Comment by AceSlash** [comment]
The output is `2.2.6`.

**Comment by ajkavanagh** [comment]
@AceSlash okay, 2.2.6 doesn't have storage pools as a feature.  They were introduced at version [2.2.8][https://github.com/lxc/pylxd/releases/tag/2.2.8].  The current release (at the time of writing) is 2.2.10.  Are you able to update?  Pypi: https://pypi.org/project/pylxd/

**Comment by AceSlash** [comment]
Okay, that explain it, thanks. So the bionic version is outdated, that's too bad, I prefer to install via apt and not via source or pip but I'll see what I can do.

Thank you for your time.
