### ISSUE TITLE
container.execute() not working

### ISSUE THREAD

**Issue by miqayel-manvelyan** [lxc/pylxd#380]
I have flask application (flask + socketio + gunicorn), and pylxd not working correctly on it.
Problem in container.execute() method. 

For example
```
print(0)
container.execute(['ls'])
print(1)
container.execute(['cd', '/var/www/html'])
print(2)
container.execute(['service', 'nginx', 'restart'])
print(3)
```

Output: 0

Please help me :(

pylxd = 2.2.10
lxd = 3.18

**Comment by ajkavanagh** [comment]
Are there no error messages?  What is the container? There's really not a lot to go on here to help you.

**Comment by miqayel-manvelyan** [comment]
Hey, @ajkavanagh,
Thanks for quick reply

No errors, I get just warnings
```
venv/lib/python3.6/site-packages/pylxd/models/_model.py:137: UserWarning: Attempted to set unknown attribute "type" on instance of "Container" key, self.__class__.__name__
0
venv/lib/python3.6/site-packages/pylxd/models/operation.py:79: UserWarning: Attempted to set unknown attribute "location" on instance of "Operation".format(key, self.__class__.__name__))
```

container  = Alpine Linux 3.10

**Running application with command:**
```
gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 wsgi:app -b 0.0.0.0:5555
```


It used to work time-to-time when running on WSGI. When I moved to Gunicorn it started not to work at all. There are some commands which don't work neither on WSGI nor on Gunicorn, like:
```
container.execute(['service', 'nginx', 'restart'])
container.execute(['cp', 'a', 'b', '-R'])
container.execute(['mv', 'a', 'b', '-R'])
```

I can thing it's something related to the socket.io, maybe they both work on socket and are conflicting. Though not sure..

Thanks again

**Comment by ajkavanagh** [comment]
Thanks for the update.  The warnings are because LXD has grown some new attributes on some of the models, and pylxd is unaware of them.  You can silence them by setting PYLXD_WARNINGS='none' in the environment before running the app which loads pylxd.

This was added in #361 -- by default one warning is printed for each attribute known about; there is an 'always' setting which prints the warning for every subsequent model load.

I think you are probably hitting #379 which I'm looking at.  An (ugly) work-around is to use subprocess.Popen and just run lxc exec directly through that; but this only works if it is on the same machine and the user has the same permissions as the pylxd user that is being used.

I may provide that as an alternative exec method, but it has the above significant issues.

**Comment by miqayel-manvelyan** [comment]
Thanks for update.
I will check again to get the latest updates,
Hope it will be fixed soon,

By the way, for those who have the same problem.
```
import subprocess

def execute(container_name, commands):
  lxc_commands = ['lxc', 'exec', container_name, '--', *commands]
  return subprocess.run(lxc_commands, capture_output=True)
```

Thanks!

**Comment by tkasidakis** [comment]
/home/tkasidakis/.local/lib/python3.6/site-packages/pylxd/models/operation.py:79: UserWarning: Attempted to set unknown attribute "location" on instance of "Operation"
  .format(key, self.__class__.__name__))

I get this message when i am using the execute() commnad . I am using lxd 4.3 from snap.

Is it the same bug, right ?

**Comment by ajkavanagh** [comment]
You are hitting the "lxd has a new attribute that pylxd doesn't know about".  It's a warning to indicate that an Operation now has a location attribute.  it's nothing to worry about unless you need the location attribute.  However, if the execute isn't actually working then you've hit this bug.

**Comment by tkasidakis** [comment]
Yes i think that a hit this bug . Fortunately subprocess.run() does the job :)

**Comment by tkasidakis** [comment]
while(1):
	svc=input() # reads the service name and loads it approprialy #
	if(svc=="list"):
		print("hello")
	else:
		n.load_service(svc)
	
def load_service(self,svcname):
existval = LXDmanager.containers.exists(svcname)
			if(existval==True):
				print("Service in a Container already exists")
				commandsToSvcConatiner=['lxc','exec',svcname,'python3',svcname+'.py']
				subprocess.Popen(commandsToSvcConatiner)
				print("OKKKKKK")
-----------------------------------------------------------------------------------------------------------------------------------------------------

Sorry for - a bit- out of the topic post but i wanted to ask something.

My container executes .py file but after that i can't read from stdin.
Any ideas why this happens ?

**Comment by ajkavanagh** [comment]
`Popen(...)` by default connects the stdin, stdout and stderr to the parent process' (i.e. your script's) stdin / stdout.  Therefore, the `print("OKKKKKK")` has no where to go.  So if the command is still running on the container, then it is still holding the stdout and thus the print in the script will be buffered.  What you really want to do is let the script run in the container that starts the service as a daemon and then exits.  At least, I suspect that is what is going on.

You only need to use `Popen(..)` if you want to communicate with the process as it is running.  i.e. send it input, etc.  Then you use the `.communicate()` method after setting up the stdin, stdout, etc. to PIPEs to do that communication.  If you are running one-shot commands, it's easier to use `subprocess.check_call()` and friends.
