### ISSUE TITLE
Support for project management

### ISSUE THREAD

**Issue by pstch** [lxc/pylxd#399]
Dear maintainers,

LXD supports "projects" since version 3.6. It would be useful to be able to manage them using `pylxd`.

Would such a feature be accepted ? Is there some work planned on this ?

I would be interested in writing the code required for this, if it's not being done currently.

Thank you for you work on this library, it has been a pleasure to use.

**Comment by sparkiegeek** [comment]
This was implemented in #427, #430 and follow-ups
