### ISSUE TITLE
Events method not usable with UNIX domain sockets

### ISSUE THREAD

**Issue by pstch** [lxc/pylxd#401]
While testing my patch in #400, I noticed that the `events()` method does not work when connecting to the daemon through an UNIX domain socket:

```
>>> client = pylxd.Client()
>>> events = client.events()
>>> events.run()
Failed to receive data
Traceback (most recent call last):
  File "/nix/store/80xg5vr1095wihvvgppw9gjplhk1l0xr-python3-3.7.6-env/lib/python3.7/site-packages/ws4py/websocket.py", line 394, in once
    b = self.sock.recv(self.reading_buffer_size)
OSError: [Errno 22] Invalid argument
```

**Comment by sparkiegeek** [comment]
Hi @pstch,

Thanks for taking the time to play with pylxd and file this issue.

The problem you're having is that you forgot to `events.connect()` before trying to `.run()` - this is covered in the [Events docs](https://pylxd.readthedocs.io/en/latest/events.html).
