### ISSUE TITLE
Why doesn't cloud-init work when creating containers which user.user-data cloud-config?

### ISSUE THREAD

**Issue by Dweller** [lxc/pylxd#418]
Why does cloud-config config user.user-data in profiles not get executed when a container with those profiles is created?

**Comment by stgraber** [comment]
It sure does get executed :)

Can you show `lxc config show --expanded NAME` for a container where it didn't work?
Then check `/var/log/cloud-init-*` files inside the container.

**Comment by Dweller** [comment]
I can confirm the issue has been solved..  Seems using a cloud-init image also helps..
