### ISSUE TITLE
Update Ubuntu packages

### ISSUE THREAD

**Issue by mazerty** [lxc/pylxd#462]
Hi !
The "python3-pylxd" packages for the Focal, Groovy and Hirsute versions of Ubuntu are still pointing to the 2.2.10
Can you push the latest version to these repositories ?
Thanks :)

**Comment by sparkiegeek** [comment]
We don't maintain the packages in Ubuntu/Debian - you're probably best contacting the Debian maintainers - https://tracker.debian.org/pkg/python-pylxd
