### ISSUE TITLE
How to create a separate disk for a container

### ISSUE THREAD

**Issue by AlifeLine** [lxc/pylxd#481]
I try to create a profile and then use this profile to create a container. Other restrictions take effect, but the size of the root directory does not.
this is my code：
![image](https://user-images.githubusercontent.com/33149119/128299174-9238cf1b-a221-44e6-8d98-31be3a748b02.png)
![image](https://user-images.githubusercontent.com/33149119/128299223-14a5837c-94fa-4e7c-9ebd-d976f933a0ba.png)
 container  df -h result：
![image](https://user-images.githubusercontent.com/33149119/128299345-5201fc53-3925-4ec1-a40e-248131f04298.png)         '
so why  root directory’s size isn't  10G

**Comment by stgraber** [comment]
Could you show `lxc config show --expanded test2`?

**Comment by AlifeLine** [comment]
> Could you show `lxc config show --expanded test2`?

![image](https://user-images.githubusercontent.com/33149119/128357931-96ed1804-1159-4d19-9c66-ef93d3261c52.png)
maybe it work,I try use dd generate zero file ,it triggered the quota. 
![image](https://user-images.githubusercontent.com/33149119/128358346-56371c00-1ed3-4eb2-bcd7-4a2c80d3c851.png)

**Comment by AlifeLine** [comment]
> Could you show `lxc config show --expanded test2`?

When I used Proxmox VE, the container was a separate virtual disk, and the difference between the two led to misunderstanding.

**Comment by stgraber** [comment]
What storage backend is this on?

zfs, lvm and ceph will have `df -h` show the limit in the container. `dir` only does if the filesystem has project quotas setup (not very common) and `btrfs` never does, though limits are enforced on btrfs through quotas.

The behavior above suggests you're on btrfs and this would indeed be the expected behavior there.

**Comment by AlifeLine** [comment]
> What storage backend is this on?
> 
> zfs, lvm and ceph will have `df -h` show the limit in the container. `dir` only does if the filesystem has project quotas setup (not very common) and `btrfs` never does, though limits are enforced on btrfs through quotas.
> 
> The behavior above suggests you're on btrfs and this would indeed be the expected behavior there.

ok thanks，I have gained knowledge.
