### ISSUE TITLE
host_info() is broken

### ISSUE THREAD

**Issue by sadig** [lxc/pylxd#49]
Hi,

given that little python script:

```python
#!/usr/bin/env python

from pylxd import api

if __name__ == '__main__':
        lxd = api.API()
        lxd.host_info()
```

I get the following traceback:

Traceback (most recent call last):
  File "./test_pylxd.py", line 7, in <module>
    lxd.host_info()
  File "/home/sadig/Projects/git.sadig/pylxd/pylxd/api.py", line 44, in host_info
    return self.hosts.host_info()
  File "/home/sadig/Projects/git.sadig/pylxd/pylxd/hosts.py", line 38, in host_info
    self.get_lxd_backing_fs(data.get('metadata')),
  File "/home/sadig/Projects/git.sadig/pylxd/pylxd/hosts.py", line 73, in get_lxd_backing_fs
    return data['environment']['backing_fs']
KeyError: 'backing_fs'

checking the 'data' hash, it seems, that the result of 'metadata' doesn't contain 'backing_fs' anymore.
The same issue is also with the 'version' key from 'metadata'

**Comment by sadig** [comment]
After checking the LXD code, it could be that some storages are not recognized.
Short infos about the system:

Storage: Local Storage with XFS as FS

**Comment by rockstar** [comment]
This function is definitely completely broken given the LXD 2.0 API. Given that it's the deprecated API, we won't be fixing it ourselves, but will gladly accept a patch.
