### ISSUE TITLE
test_images failing due to dir misconstruction

### ISSUE THREAD

**Issue by Itxaka** [lxc/pylxd#5]
```
# itxaka at zeus in ~/projects/pylxd on git:master x [15:20:21]
$ python -V
Python 2.7.9
(.venv)
# itxaka at zeus in ~/projects/pylxd on git:master x [15:20:23]
$ which python
/home/itxaka/projects/pylxd/.venv/bin/python
(.venv)
# itxaka at zeus in ~/projects/pylxd on git:master x [15:20:27]
$ pwd
/home/itxaka/projects/pylxd
```
Running tox from the root dir
Some of the tests wil fail because they are trying to get the worng local image:
```IOError: [Errno 2] No such file or directory: '/home/itxaka/projects/images/lxd.tar.xz'```

Probably due to this 3 lines at https://github.com/lxc/pylxd/blob/master/pylxd/tests/test_image.py#L22-L24

```
TESTDIR = os.path.dirname(os.path.abspath(__file__))
ROOTDIR = os.path.normpath(os.path.join(TESTDIR, '..', '..', '..'))
IMAGE = os.path.join(ROOTDIR, 'images', 'lxd.tar.xz')
```

Not sure why this is there. On the repo, the images dir is under the test dir, so the first ```TESTDIR``` should already contain the proper path to the test dir.

**Comment by rockstar** [comment]
I'm not sure this still occurs. This api has also been deprecated. If it's still occurring on your system, please open a new issue.
