### ISSUE TITLE
Latest release 2.3.0 or 2.3.1

### ISSUE THREAD

**Issue by fliiiix** [lxc/pylxd#500]
Is it just an mistake that the latest release here is still 2.3.0 and not 2.3.1?

![image](https://user-images.githubusercontent.com/1682954/151950796-813b612b-a05f-4998-8d75-f87dd40650a6.png)

**Comment by stgraber** [comment]
Github doesn't automatically create releases from tags. I've now created a release (though empty) so the UI lines up.
