### ISSUE TITLE
Create operations can fail silently

### ISSUE THREAD

**Issue by candlerb** [lxc/pylxd#78]
Here is a case in which a create operation will appear to return successfully, but the container has not been created. The client has no idea why.

~~~
from pylxd import api
CONTAINER_NAME="nettest"

config = {
  'source': {
    'alias': '16.04', 'type': 'image', 'mode': 'pull', 'protocol': 'lxd', 'server': 'https://images.linuxcontainers.org'},
  'name': CONTAINER_NAME,
  'profiles': ['default']
}

lxd = api.API()
lxd.container_init(config)
if lxd.container_defined(CONTAINER_NAME):
    print("Container is running")
else:
    print("Whoops - please report a bug!")
~~~

Prints: `Whoops - please report a bug!`

Of course, almost certainly I'm sending the wrong REST parameters here. The issue is that presumably pylxd is getting some sort of error response over HTTP, but it is not catching it and turning it into an exception.

**Comment by stgraber** [comment]
You indeed are passing it invalid input :)

alias set to ubuntu/xenial/amd64 should do the trick, or pass 16.04 but then set protocol to simplestreams and server to https://cloud-images.ubuntu.com/releases

**Comment by candlerb** [comment]
I get the same "Whoops" response with this config too:

~~~
config = {
  'source': {
    'alias': '16.04', 'type': 'image', 'mode': 'pull', 'protocol': 'simplestreams', 'server': 'https://cloud-images.ubuntu.com/releases'},
  'name': CONTAINER_NAME,
  'profiles': ['default']
}
~~~

But in any case, would you agree that the REST API should return an error for bad parameters, and that pylxd should return the error to the client, probably as an exception?

**Comment by stgraber** [comment]
Yeah, pylxd should definitely do a better job at catching errors here

**Comment by candlerb** [comment]
Just for the record, this config *does* work:

~~~
config = {
  'source': {
    'alias': 'ubuntu/xenial/amd64', 'type': 'image', 'mode': 'pull', 'protocol': 'lxd', 'server': 'https://images.linuxcontainers.org'},
  'name': CONTAINER_NAME,
  'profiles': ['default']
}
~~~

It creates a container (in stopped state)

**Comment by jpic** [comment]
Should pylxd raise an exception if it gets a response with a status code > 400 ?

**Comment by candlerb** [comment]
I [think it should](https://github.com/lxc/pylxd/issues/77#issuecomment-219459693)

However I already added that patch, so I believe this is different issue.

Here the job submission is accepted, pylxd polls for completion, but pylxd is apparently ignoring the result of the job.

**Comment by jpic** [comment]
Raising an exception with status code >= 400 will inhibit specific error handling ie. in [Container.get](https://github.com/lxc/pylxd/blob/master/pylxd/container.py#L36) - integration tests caught it.

However, raising a RuntimeError on status_code >= 500 works well, adding it to my PR then.

**Comment by rockstar** [comment]
This is using the deprecated API (though forwarded to the public API for backwards compatibility), which was deprecated for this very reason. If you have similar issues (and by the looks of #77, you do) with the newer API, please report those issues.
