### ISSUE TITLE
container operations and wait_operation not in sync

### ISSUE THREAD

**Issue by mgwilliams** [lxc/pylxd#8]
Container operations return an `operation` url that looks like `/1.0/operations/c212109b-2690-4c4e-a3a0-80c7bf1bd3bc`. When this value is passed to `wait_operation`, `/1.0/operations/` is again prepended, resulting in a request of `/1.0/operations/1.0/operations/c212109b-2690-4c4e-a3a0-80c7bf1bd3bc`.

**Comment by uglide** [comment]
:+1:
