### ISSUE TITLE
Run integration tests on CI

### ISSUE THREAD

**Issue by jpic** [lxc/pylxd#88]
Currently, master passes unit tests with a an lxd REST API mock, but the code is not completely compatible with actual LXD REST API, and CI isn't warning commiters. We have great integration tests, which we can run both on a local and remote lxd instance. They help greatly in finding bugs, ie. lxd http rest api has been updated upstream.

Can we have CI for integration tests ?

This would help finding bugs earlier in the software.

Thanks !

**Comment by rockstar** [comment]
If the unit tests aren't matching up with the lxd API, the unit tests need to be fixed. The integration tests will be run in LXD's upstream jenkins, when the lxd team has time to get that configured.

**Comment by jpic** [comment]
Awesome, shouldn't we can leave this open until it's configured upstream ?
