### ISSUE TITLE
Host documentation in HTML format

### ISSUE THREAD

**Issue by jpic** [lxc/pylxd#89]
Currently, documentation is maintained with sphinx in RST format in the doc directory.

It would be great if we could host an HTML version.

Just in case, note that readthedocs.org provides a free service with a github hook to update the documentation when changes are merged. It also allows to switch versions allowing to read the docs for the current master or latest stable release or even older releases.

**Comment by rockstar** [comment]
http://pylxd.readthedocs.io/en/latest/

**Comment by jpic** [comment]
Thank you sooo much you :guitar:
